Repository I2PC/xmipp, pull requests merged in 2024-09, with the labels that each got.

#902 Added check with multiple CUDA versions
  .github/workflows/build.yml
  CMakeLists.txt
  src/xmipp/CMakeLists.txt
Labels: enhancement

#908 Extra check: without CUDA
  .github/workflows/build.yml
Labels: enhancement

#912 Fix devel installation command in docs
  README.md
Labels: documentation

#913 Fix missing API calls
  installer/api.py
  installer/main.py
  xmipp
Labels: bug
