Repository I2PC/xmipp, pull requests merged in 2025-01, with the labels that each got.

#973 syntax error
  .github/workflows/build.yml
  xmipp
Labels: bug, release

#974 Master to devel
  .github/workflows/build.yml
  CHANGELOG.md
  installer/api.py
  installer/constants/main.py
  installer/constants/parser.py
  installer/constants/versions.py
  installer/main.py
  installer/utils.py
  xmipp
Labels: release

#982 Delete redundant command
  xmipp
Labels: enhancement
